// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgizXRvvLoqBgWYIchaDzKj6DasO3gq28',
    appId: '1:195875098290:web:0b25380559a17c983743ab',
    messagingSenderId: '195875098290',
    projectId: 'sya-revert-app-47b8b',
    authDomain: 'sya-revert-app-47b8b.firebaseapp.com',
    storageBucket: 'sya-revert-app-47b8b.firebasestorage.app',
    measurementId: 'G-DG22Y44ZNJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuqsRfzPP7atT6QxEqFNzeK9gsoszP9lM',
    appId: '1:195875098290:android:ac04b02fe27ef7203743ab',
    messagingSenderId: '195875098290',
    projectId: 'sya-revert-app-47b8b',
    storageBucket: 'sya-revert-app-47b8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuGhxRAebhmYPscSCvq69sKdAOB9ozMvA',
    appId: '1:195875098290:ios:c39a461273e3d9eb3743ab',
    messagingSenderId: '195875098290',
    projectId: 'sya-revert-app-47b8b',
    storageBucket: 'sya-revert-app-47b8b.firebasestorage.app',
    iosBundleId: 'com.syamuslim.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuGhxRAebhmYPscSCvq69sKdAOB9ozMvA',
    appId: '1:195875098290:ios:25f9c23a682a5db33743ab',
    messagingSenderId: '195875098290',
    projectId: 'sya-revert-app-47b8b',
    storageBucket: 'sya-revert-app-47b8b.firebasestorage.app',
    iosBundleId: 'com.example.muslimCommunity',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDgizXRvvLoqBgWYIchaDzKj6DasO3gq28',
    appId: '1:195875098290:web:64823749a43fef143743ab',
    messagingSenderId: '195875098290',
    projectId: 'sya-revert-app-47b8b',
    authDomain: 'sya-revert-app-47b8b.firebaseapp.com',
    storageBucket: 'sya-revert-app-47b8b.firebasestorage.app',
    measurementId: 'G-3WNRRF68XM',
  );
}
